verb_list = {
    'to be(permanent)': 'ser',
    'to be(temporary)': 'estar',
    'to have': 'ter',
    'to be able/can': 'poder',
    'to go': 'ir',
    'to do': 'fazer',
    'to have/posses/own': 'haver',
    'to say': 'dizer',
    'to see': 'ver',
    'to give': 'dar',
    'to know(about)': 'saber',
    'to want': 'querer',
    'to owe/must/ought': 'dever',
    'to become/remain/stay': 'ficar',
    'to pass': 'passar',
    'to come': 'vir',
    'to arrive': 'chegar',
    'to speak': 'falar',
    'to leave': 'deixar',
    'to take': 'levar',
    'to find': 'encontrar',
    'to think': 'pensar',
    'to seem': 'parecer',
    'to present': 'apresentar',
    'to know(be acquainted)': 'conhecer',
    'to ask for': 'pedir',
    'to live': 'viver',
    'to open': 'abrir',
    'to end': 'acabar',
    'to happen': 'acontecer',
    'to add': 'acrescentar',
    'to claim': 'afirmar',
    'to help': 'ajudar',
    'to announce': 'anunciar',
    'to increase': 'aumentar',
    'to place': 'colocar',
    'to start': 'começar',
    'to get': 'conseguir',
    'to count': 'contar',
    'to continue': 'continuar',
    'to create': 'criar',
    'to fill': 'cumprir',
    'to defend': 'defender',
    'to enter': 'entrar',
    'to send': 'enviar',
    'to write': 'escrever',
    'to expect/wait': 'esperar',
    'to explain': 'explicar',
    'to win': 'ganhar',
    'to include': 'incluir',
    'to play': 'jogar',
    'to keep/maintain': 'manter',
    'to mark': 'marcar',
    'to show': 'mostrar',
    'to pay': 'pagar',
    'to lose/miss': 'perder',
    'to allow': 'permitir',
    'to consider': 'considerar',
    'to need': 'presicar',
    'to perform/direct': 'realizar',
    'to recieve': 'receber',
    'to leave': 'sair',
    'to assure/ensure/guarantee': 'garantir',
    'to follow': 'seguir',
    'to predict': 'prever',
    'to publish': 'publicar',
    'to refer': 'referir',
    'to try': 'tentar',
    'to reveal': 'revelar',
    'to render': 'tornar',
    'to work': 'trabalhar',
    'to use': 'usar',
    'to use/utilize': 'utilizar',
    'to win': 'vencer',
    'to return': 'voltar',
}

question_dict = {
    'adeus': 'goodbye',
    'hoje': 'today',
    'hora': 'hour',
    'longe': 'far',
    'mau': 'bad',
    'perto': 'near',
    'segundo': 'second',
    'talvez': 'maybe',
    'ontem': 'yesterday',
    'bom': 'good',
    'gato': 'cat',
    'semana': 'week',
    'amanhã': 'tomorrow',
    'fazer': 'make',
    'loga': 'shop',
    'sorrir': 'smile',
    'poder': 'can',
    'usar': 'use',
    'ir': 'go',
    'vir': 'come',
    'rir': 'laugh',
    'ver': 'see',
    'café': 'coffee',
    'cerveja': 'beer',
    'chá': 'tea',
    'vinho': 'wine',
    'não': 'no',
    'delicioso': 'delicious',
    'segunda-feira': 'monday',
    'terça-feira': 'tuesday',
    'quarta-feira': 'wednesday',
    'quinta-feira': 'thursday',
    'sexta-feira': 'friday',
    'sábado': 'saturday',
    'domingo': 'sunday',
    'maio': 'may',
    'janeiro': 'january',
    'fevereiro': 'feburary',
    'março': 'march',
    'abril': 'april',
    'junho': 'june',
    'julho': 'july',
    'agosto': 'august',
    'setembro': 'september',
    'outubro': 'october',
    'novembro': 'november',
    'dezembro': 'december',
    'água': 'water',
    'frango': 'chicken',
    'carneiro': 'lamb',
    'peixe': 'fish',
    'pé': 'foot',
    'perna': 'leg',
    'cabeça': 'head',
    'braço': 'arm',
    'mão': 'hand',
    'dedo': 'finger',
    'corpo': 'body',
    'estômago': 'stomach',
    'costas': 'back',
    'peito': 'chest',
    'enfermeira': 'nurse',
    'funcionário': 'employee',
    'policial': 'police officer',
    'cozinheiro': 'cook',
    'engenheiro': 'engineer',
    'médico': 'doctor',
    'gerente': 'manager',
    'professora': 'teacher',
    'programador': 'programmer',
    'vendedor': 'salesman',
    'ano': 'year',
    'bonito': 'beautiful',
    'feio': 'ugly',
    'difícil': 'dificult',
    'minuto': 'minute',
    'calendário': 'calendar',
    'sim': 'yes',
    'zunido': 'buzz',
    'felicidade': 'happiness',
    'paixão': 'passion',
    'mãe': 'mother',
    'alguém': 'someone',
    'verdade': 'truth',
    'ninguém': 'no one',
    'dinheiro': 'money',
    'outro': 'other',
    'apenas': 'only',
    'antes': 'before',
    'sempre': 'always',
    'também': 'also/too',
}
